### PR TITLE
use the HTTP from the server as this is where it is located.

### PR DESCRIPTION
**Pull request by KasperFranz**
This got mine to work on a lumen installation :) or atleast it got it to recieve the checksum

### CODE REVIEW

**Comment by danielboendergaard** [comment]
How do you instantiate the Request object? Try `Request::createFromGlobals()`

**Comment by KasperFranz** [comment]
The request object is instanced through the Lumen layer (used as a param on the function in the controller)

**Comment by danielboendergaard** [comment]
Can you test it using `Request::createFromGlobals()`?

**Comment by KasperFranz** [comment]
Now I'm getting the error with the server method used in this PR, trying to revert to the official repo instead of my fork and see how that goes. 

not sure why it worked on my vagrant box

**Comment by KasperFranz** [comment]
It was a local problem I guess

**Pull request closed without merging**
